### ISSUE TITLE
Use of buttons

### ISSUE THREAD

**Issue by ghost** [softbankrobotics-labs/pepper-gamepad#1]
Hello,

Apart from joysticks, I'd like to know if it is possible to give use to the other buttons of the controller such as A, B, X or Y for any action like Say something or even launch other apps.

Thank you!

**Comment by alexandre-roux** [comment]
Hi,
Yes this is possible! The project is divided in two parts: a sample app and a library. As an example, we only pass the values of the joysticks to the library, but you can map the controller keys to run other actions. You will find more about this in the official reference: https://developer.android.com/training/game-controllers/controller-input.html#kotlin
The library only handles the robot movements, if you want to launch other robotic actions, you will have to do this in the sample app.
I hope this answers you question, feel free to reach us if needed!

**Comment by d16310** [comment]
Hello.

How can I implement that the pepper speaks when I actually press the A button?

**Comment by alexandre-roux** [comment]
Hi,
Sorry for the late answer, here is the code you'll need:
```
    override fun onKeyDown(keyCode: Int, event: KeyEvent?): Boolean {
        if (keyCode == KeyEvent.KEYCODE_BUTTON_A) {
            SayBuilder.with(qiContext)
                .withText("Hello")
                .buildAsync()
                .andThenConsume {
                    it.async().run()
                }
        }
        return super.onKeyDown(keyCode, event)
    }
```

**Comment by Schruser** [comment]
Hi!
Is it possible to implement that Pepper opens another App when I press a button?

**Comment by EmileKroeger** [comment]
Hi Schruser, sure, you can launch another activity with an intent: https://developer.android.com/training/basics/firstapp/starting-activity

**Comment by alexandre-roux** [comment]
Hello,
Yes this is possible, for instance if you want to open the app with `com.android.example` package name when pressing the A button:
```
    override fun onKeyDown(keyCode: Int, event: KeyEvent?): Boolean {
        if (keyCode == KeyEvent.KEYCODE_BUTTON_A) {
            val launchIntent = packageManager.getLaunchIntentForPackage("com.android.example")
            if (launchIntent != null) {
                startActivity(launchIntent)
            }
        }
        return super.onKeyDown(keyCode, event)
    }

```
More information on how to handle gamepad button presses: https://developer.android.com/training/game-controllers/controller-input.html#kotlin
More information on how to launch an Activity from another Application in Android: https://stackoverflow.com/questions/3872063/how-to-launch-an-activity-from-another-application-in-android

**Comment by Schruser** [comment]
Hello, thank you for the help!

I´d like to start an app  with a button, which is already installed on the pepper tablet. Therefore i don´t have a package name, is this still possible?

**Comment by alexandre-roux** [comment]
Hello,
You can use `PackageManager` to list all the apps installed on the tablet and get an `Intent` to launch a specific app:
```
                val packages = packageManager.getInstalledApplications(PackageManager.GET_META_DATA)
                for (packageInfo in packages) {
                    Log.d(TAG, "Installed package: " + packageInfo.packageName)
                    val launchIntent = packageManager.getLaunchIntentForPackage(packageInfo.packageName)
                    // If you want to launch this app:
                    //startActivity(launchIntent)
                }
```
More information here: https://stackoverflow.com/questions/2695746/how-to-get-a-list-of-installed-android-applications-and-pick-one-to-run
