### ISSUE TITLE
ボタンで発話

### ISSUE THREAD

**Issue by d16310** [softbankrobotics-labs/pepper-gamepad#5]
こんにちは。

A、B、X、Yなどを押した時に発話を行うには、どのように記述するのが良いのでしょうか？
様々試してみましたがうまくいきませんでした。
(例)Aボタン　押す　->ペッパーが"Hello"と発話

ありがとうございました！

**Comment by alexandre-roux** [comment]
Hello,
Please see [issue#1](https://github.com/softbankrobotics-labs/pepper-gamepad/issues/1).
Thanks
