### ISSUE TITLE
Gamepad Control through Wi-Fi

### ISSUE THREAD

**Issue by evrentuna** [softbankrobotics-labs/pepper-gamepad#6]
Hello,

Firstly, I would like to thank you for this nice and useful work. But I am wondering if you have another version gamepad control by using WiFi? Moreover, maybe, the gamepad can be any application on a smart phone, etc.

Thanks a lot!

**Comment by alexandre-roux** [comment]
Hi,
I think you'll find the version you need in this project: https://github.com/softbankrobotics-labs/pepper-telepresence-toolkit
Have a look at the "pepper-telepresence-control" library, the library interprets JSON commands to make the robot move.
Please tell me if it helped you!
