### ISSUE TITLE
Animations not playing when the gamepad library is running

### ISSUE THREAD

**Issue by Gudzenko** [softbankrobotics-labs/pepper-gamepad#7]
Hello,

I integrate gamepad library to my program, but all animations not playing. Is it possible to stop RemoteRobotController ?

**Comment by alexandre-roux** [comment]
Hello,

Do you have error messages in the logcat when animations aren't working?
If you want to make the robot stop moving, call `remoteRobotController.updateTarget(0.0, 0.0, 0.0, 0.0)`
