### ISSUE TITLE
activate "Human Behaviour" and "Speech Control" while Gamepad App

### ISSUE THREAD

**Issue by Schruser** [softbankrobotics-labs/pepper-gamepad#8]
Hello !

Is there a way to implement the Human Behavior of Pepper in the gamepad App?

How is it possible to implement speech control in the gamepad app?

I would like to activate Pepper replaying to Questions while beeing in the Gamepad App.

Another Question is: Can I change the language, which Pepper speaks (for example to German) ?

**Comment by alexandre-roux** [comment]
Hi,
Here is an article explaining how to install a language package and get speech recognition in new languages: https://developer.softbankrobotics.com/blog/lets-make-pepper-and-nao-speak-second-language
I'm not sure to understand the others questions; what do you mean by "Human Behavior"? If you want to implement a Chat, see this article: https://developer.softbankrobotics.com/pepper-qisdk/api/conversation/reference/chat
