### ISSUE TITLE
Pepper stops when driving forward - Gamepad Application

### ISSUE THREAD

**Issue by christiangebel** [softbankrobotics-labs/pepper-gamepad#9]
Hello, thank you for this application! Actually we do have a problem when the robot should drive foreward. Sometimes it drives and stops within 1 or 2 seconds later . Is there anyone else who has the same problem? 
Maybe it has something to do with the sensor system? 

Thank you! 

FYI: 
XBOX One Controller in use

**Comment by alexandre-roux** [comment]
Hi,
You have to keep the joystick in the position corresponding to the direction where you want Pepper to go. If you still have difficulties making the robot move, make sure that there are no obstacles around Pepper (including you) and that the ground is flat. More information here: https://developer.softbankrobotics.com/pepper-qisdk/api/motion/reference/goto#need-for-error-handling
I hope it'll help you, do not hesitate to reach out to us if you still have issues!
Regards

**Comment by christiangebel** [comment]
Hi, 
thank you for the answer. The interesting thing is that when the robot was not in use the control works without problems. When the robot is in use for a long time, the control system no longer works or works poorly.

**Comment by alexandre-roux** [comment]
Hi,
Maybe there's conflict with animation movements from other apps?

**Comment by alexandre-roux** [comment]
Hi,
I just pushed a new version (1.0.4) adding start() and stop() methods for the RemoteRobotController object. You can use it to stop the RemoteRobotController before running a custom animation and then restarting it again.
Can you tell me if it helps?
Regards

**Comment by christiangebel** [comment]
Hi, 

many thanks for the new version. It isn't still working. But we guess it has something to do with the robot's hardware. It will be send to Paris for a checkup. 

Regards
